// Generated by CoffeeScript 1.3.3
(function() {
  var Filter;

  Filter = (function() {

    function Filter() {}

    Filter.prototype.convolve = function() {
      return alert("Unimplemented");
    };

    return Filter;

  })();

}).call(this);
